### ISSUE TITLE
jq error

### ISSUE THREAD

**Issue by leejosh** [Iserv-Group/Zabbix-Meraki#1]
on the last line of meraki_status.sh jq throws an error
echo $dev | jq > $output_folder"meraki.json"

it should be:
echo $dev | jq . > $output_folder"meraki.json"

**Comment by zdegraaf** [comment]
Thanks for the comment. Based on feedback that I've been getting it looks like jq functions slightly different with different distros, so my Ubuntu install doesn't need the dot, but can work with it. Other distros require it on commands like this though so I am working to add it anywhere it's needed and have corrected it in the place you pointed out.
